### ISSUE TITLE
About CnCommon

### ISSUE THREAD

**Issue by achinastone** [cnpack/cnvcl#10]
CnCommon.pas
function CnUtf8ToAnsi(const Text: AnsiString): AnsiString;
Need to be changed to
function CnUtf8ToAnsi(const Text: UTF8String): AnsiString;

In Delphi 10.3
CnCustBuild.dpr can not display the wizard name and the comments

**Comment by shanzhashu** [comment]
Delphi 5 does not have UTF8String definition so we use AnsiString. We can add UTF8String definition in CnCommon when Delphi 5.

CnCustBuild tool is not for Unicode Compiler such as Delphi 2009 or above. We'll modify it to Unicode Compiler.
