### ISSUE TITLE
Support 64 bit

### ISSUE THREAD

**Issue by Starina123** [cnpack/cnvcl#11]
Do you plan to add support for the Win64 platform?

**Comment by shanzhashu** [comment]
In fact, many Units, especially in Source/Common, both supports Win32 and Win64, even some including MacOS.
But all supporting for Win64 will be a big workload. We’ll try it.

**Comment by shanzhashu** [comment]
After some checking and committing, these units do not support win64:

Source\Common\CnObjAuto.pas
Source\Graphics\CnOpenGLPaintBox.pas
Source\NonVisual\CnASCommon.pas
Source\NonVisual\CnASHostServices.pas',
Source\NonVisual\CnASIDispatchProxy.pas
Source\NonVisual\CnASInvoker.pas
Source\NonVisual\CnHardwareBreakpoint.pas
Source\NonVisual\CnInProcessAPIHook.pas
Source\NonVisual\CnMemorySearch.pas

Other units support Win64. Now I modified Packages\Delphi103R\CnPack_D103R.dproj. We can add Win64 configuration to it and compile OK.

But for design time package, for Dephi IDE is 32-bit, we seems can NOT implement a 64-bit package with some Component Editors.

**Comment by Starina123** [comment]
Thanks.
