### ISSUE TITLE
项目里的介绍全改成中文描述，中文优先。。。

### ISSUE THREAD

**Issue by wwq0071** [cnpack/cnvcl#13]
项目里的介绍全改成中文描述，中文优先。。。
明明大家都是中国人，中国人开发的控件包，还要打上英文描述，这是组织上缺乏安全感还是没自信？
不要说我看不懂英文，这跟个人毛关系都没有。
不要说这是行业规范，毛规范，中国的环境下规范范文也是中文。
别给人一看就觉得是外国佬的写的，这是中国人写的，应该有这份自信，不要以为挂着一份英文说明书就觉得这东西好。

**Comment by Atol-codetoad** [comment]
大家好  cn pack team。 我是俄罗斯人 和 我用你的程序  请您 不要删除帮助英语。但是我的一点点汉语  和  很多话我听不懂。Заранее спасибо 。Надеюсь Вы продолжите помогать всему миру разработчиков Дельфи。 С уважением / 祝好您

**Comment by codegame** [comment]
在github上做为一个开源的组件面向的是世界，自然是要以世界标准语言为优先考虑，这里优先讨论的是技术。
