### ISSUE TITLE
大佬， 为啥用cnpack的sm4算出来的和C#、java的不一样呢？

### ISSUE THREAD

**Issue by Arvin-Feng** [cnpack/cnvcl#14]

**Comment by shanzhashu** [comment]
分组加密考虑的因素有很多：

1、每块的加密算法（DES/AES/SM4等）
2、数据分块的每块大小（128/192/256等）
3、块与块之间的运算模式（ECB/CBC等）
4、数据不满足整数块时如何填充（PKCS1/PKCS7等）
5、密文是否要转变成可读的（Hex/Base64等）

两个加密机制，但凡有一处和所需的不一样，加密出来的结果就对不上号。

**Comment by Arvin-Feng** [comment]
![image](https://user-images.githubusercontent.com/26560662/117979823-e7629b00-b365-11eb-813b-3dfe78cda312.png)

服务是Java的， 用C#的sm4库加密可以验证通过， 但Delphi不行， 一样的key和字符串，ecb ， 算出来的码和C#的不一样，烦啊， 看来只能用C#封装个库给Delphi调用了。

**Comment by shanzhashu** [comment]
要先确定一下字符串是什么编码。
猜测你的Java和C#都是将字符串转成了UTF8后加密，但Delphi没有指定UTF8，导致加密的原始内容不同。

**Comment by Arvin-Feng** [comment]
原文: abc
key: 5ed70848fa4f5436
模式：ECB

这是C#和在线工具的计算结果， 也一样的。
![image](https://user-images.githubusercontent.com/26560662/118061005-ab135700-b3c6-11eb-8b73-9d38bd200fb0.png)

![image](https://user-images.githubusercontent.com/26560662/118061091-d9913200-b3c6-11eb-9cbd-ceff9cebda54.png)

以下是cnpack自带Demo计算的结果：
![image](https://user-images.githubusercontent.com/26560662/118061219-1a894680-b3c7-11eb-9a87-058851fcf748.png)

**Comment by shanzhashu** [comment]
4、数据不满足整数块时如何填充（PKCS1/PKCS7等）
——从图中看出是填充方式的差异。你的工具用的是PKCS7的填充，我们的工具用的是尾部加#0填充。

**Comment by Arvin-Feng** [comment]
哦， 了解，谢谢。

**Comment by shanzhashu** [comment]
CnPack的SM4库改用PKCS7Padding的方式加密后，和楼主提供的结果一致。

**Comment by Arvin-Feng** [comment]
请问， 怎么改啊，demo里没看到参数啊。

**Comment by Arvin-Feng** [comment]
哦， 看到了， 我试试。

**Comment by shanzhashu** [comment]
嗯，我更新了Demo，加上了Padding这个选项供测试。

**Comment by Arvin-Feng** [comment]
非常感谢，辛苦了。
