### ISSUE TITLE
Transparent property for TCnAAScrollText

### ISSUE THREAD

**Issue by chicknsoup** [cnpack/cnvcl#15]
Hi there,

Currently, TCnAAFadeText, TCnAAMarqueeText, TCnAAText support Transparent. Is it possible that we have Transparent property for TCnAAScrollText?

**Comment by shanzhashu** [comment]
TCnAAScrollText is different with other controls.

If need TCnAAScrollText's transparent support, we must use GDI+ to draw alpha/transparent  Text, which only supports on Delphi XE2 or above.
And need a lot of time to do this work...

**Comment by chicknsoup** [comment]
Oh, I thought it's similar to the `TCnAAMarqueeText` control with just different direction. It would be nice to have the property implemented. I know it takes time though.  Thanks.

**Comment by shanzhashu** [comment]
Basically done. TCnAAScrollText support transparent property for ALL Delphi versions without GDI+.

**Comment by chicknsoup** [comment]
Great work. Thank you.
