### ISSUE TITLE
CnRSA签名后无法验签

### ISSUE THREAD

**Issue by luwei0711** [cnpack/cnvcl#16]
1、cnrsa接口不是太方便签名（还有中文问题，base64），稍微有些不那么亲民^_^
2、签名后内内容在网上《在线RSA加密解密》类验签网站上无法验签，会提示异常，公钥请保留-------BEGIN PRIVATE KEY--------------及---------END PRIVATE KEY----------

**Comment by shanzhashu** [comment]
1、CnRSA目前的接口支持File和Stream，签名内容输出支持File和Stream，理论上满足要求，如果需要其他更加方便的输入和输出可以提详细需求，我们考虑实现。

2、不太明白。你贴的这个异常看上去似乎是你提交给那个网站的公钥内容不对，而不是CnRSA拿私钥签名签出来的不对？
