### ISSUE TITLE
请教：SM4使用java中的byte数组加密结果不一致

### ISSUE THREAD

**Issue by Yang-Ya-Chao** [cnpack/cnvcl#19]
java的key: byte[] keyBytes={17,34,79,88,-120,16,64,56,40,37,121,81,-53,-35,85,102}
加密模式：ECB
填充模式：PKCS7
请教怎么使用cnvcl的SM4模块加密呢
使用如下代码加密的结果与java不一致：
--CNVCL加密代码
const
  TmpKeytmp: array[0..15] of Byte =
   (17, 34, 79, 88, 255 - 120, 16, 64, 56, 40,
    37, 121, 81, 255 - 53, 255 - 35, 85, 102);
procedure TFormCrypt.btnSm4Click(Sender: TObject)
  function ArraytoTbytes(bs: array of byte): Tbytes;
  begin
    setlength(Result, Length(bs));
    Move(bs[0], Result[0], Length(bs));
  end;
var
  Output: AnsiString;
  Len: Integer;
  TmpSm4Iv: array[0..15] of Byte;
  IvStr: AnsiString;
  s: ansistring;
  m, n: string;
  KeyBytes, ResBytes, DataBytes: TBytes;
begin
  Len := Length(AnsiString(MMSm4.Text));
  if Len < 16 then
    Len := 16
  else
    Len := (((Len - 1) div 16) + 1) * 16;
  SetLength(Output, Len);
  ZeroMemory(@(Output[1]), Len);
  KeyBytes := ArraytoTbytes(TmpKeytmp);//TEncoding.Default.GetBytes(MMKey.Text);
  DataBytes := TEncoding.Default.GetBytes(MMSm4.Text);
  BytesAddPKCS7Padding(DataBytes, SM4_BLOCKSIZE);
  ResBytes := SM4EncryptEcbBytes(KeyBytes, DataBytes);
  MMCode.Text := BytesToHex(ResBytes);
end;

**Comment by shanzhashu** [comment]
把Java的写法以及待加密的明文和各自加的密文都贴出来吧，问题很可能在编码上。

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shanzhashu** [comment]
这休假休的可够长的……

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yang-Ya-Chao** [comment]
抱歉哈，没有关注iss消息，这个是接到的对方文档说明
加密说明
1、整个接口的 XML 以密文传输，适用国密 sm4 国家已开放算法，提供的是 java 加
密，解
密 jar,如果是 java 后台在引入 jar 后可直接调用。
2、加密调用 common-endecrypt-2.0.0.jar 中的 Sm4HexEn.encode("明文")方法;
3、解密调用 common-decrypt-2.0.0.jar 中的 Sm4HexDe.decode("密文");方法
4、如果非 java 程序进行加解密需自行实现，有两种方式【自行实现】或【将 JAR 转
DLL】
算法使用 sm4 的 ECB 模式
算法密钥 byte[] keyBytes = {
17, 34, 79, 88, -120, 16, 64, 56, 40, 37, 121, 81, -53, -35, 85, 102 };
自行实现算法时不要调用 Base64 编码，需直接将加密结果转成 16 进制
5,如果是调用动态库，可将 jar 包转成 DLL 来调用，这样最简单

**Comment by Yang-Ya-Chao** [comment]
密文：
C41D868B258804F75054A2A1E590A132A4798DA8E20D09E101489E3F4758CF87D6F5B36BEA7DD63BBE6DC5A1FB53D064F8CB252AAD3CBB570F4ECD54DBBAAC5CF36811FD8C922C9C752153A355A5753AF976B3070D391E583F7BD71FB38D7F411F58139C3736276DED122B0CE9E83F771847C7F00EA1BC8CC830B3C7BA5608DE155A5BA02B0AE0E4047B4061CEF187B5A323D0B68413B020BA87DCDD247D4EB1375B75EAEA1E95F440B7C803991000A91404E13DB4E2767F29F9175FBC56E1084A39E2DE07DB1739A91BF87C51C15B452B8ABD14712F6014D4F86BFD79F2D32CD9D258E601ECA2CD7965AAE181248D7CCF517DF183B7574AED9FFFD9C4BC600D4316D0CC385CA7601B2C63585E9D9880E8D275ED99619823FBBC2D91DFE367BC9CCAC97035A1C7E68EA49D34E100EFB7CC16541499F3452ECC7F48840C1E556232C2F41126C8B4B9C415382867D40BA7DF00E6B0FA6645951BF67025AC8775EFD79AFBAD6476E8981B07FFE16269521A9647312061470D3803B9303B95F1DE253B7A06EB4257EB2C9DFE2021A7F2BD7DA5C7568AFE0A60278330CB435E4331775598076E37CF283787747A0E613CA82624FF4E8D25C805671C0C9EB537D21A6DF76B7B1113456021B931407BA8C17FF04C81C4C32992B11BB028AED90DF856F7DC7F1B76891A6832B11B98E059D0FA8F0313D495172A4B796806EB4B8DFA69CC87E47D9586050F7A61ECBDB48BFFF6A906613910592441659D2BBD2F9F5B559A95FAD4926E5B25CCB4963C5934F14E5A2EFC9FF48CFE3B15C8443D2680051400AA25D1E134B46C045F9E2B43E484CEA6FAAC5FCE07387982F5A2DFF5DD073045

明文：
<YL_ACTIVE_ROOT>
    <CFDDM>0001</CFDDM>
    <YLJGDM>451209209</YLJGDM>
    <YLJGMC>绵阳市中心医院</YLJGMC>
    <JZKSDM>0130</JZKSDM>
    <JZKSMC>肝胆外科</JZKSMC>
    <JZLSH>22050643</JZLSH>
    <JZBQDM></JZBQDM>
    <JZBQMC></JZBQMC>
    <JZYSDM>010052</JZYSDM>
    <JZYSMC>龚大钊</JZYSMC>
    <MZZYBZ>1</MZZYBZ>
    <KH>602849075</KH>
    <KLX>01</KLX>
    <HZZJHM>510702196708102626</HZZJHM>
    <HZZJLX>01</HZZJLX>
    <HZXM>张小华</HZXM>
    <HZXB>2</HZXB>
    <CSRQ>1944-10-26</CSRQ>
    <LXDH>18084872935</LXDH>
    <JZRQ>2022-05-22</JZRQ>
</YL_ACTIVE_ROOT>

**Comment by Yang-Ya-Chao** [comment]
[新建文本文档.txt](https://github.com/cnpack/cnvcl/files/10274805/default.txt)
密文跟明文我放这里了，这个是java给的示例

**Comment by shanzhashu** [comment]
不同端的分组加密考虑的因素有很多： 
1、每块的加密算法（DES/AES/SM4等）
2、数据分块的每块大小（128/192/256等） 
3、块与块之间的运算模式（ECB/CBC等） 
4、数据不满足整数块时如何填充（PKCS1/PKCS7等）
5、密文是否要转变成可读的（Hex/Base64等） 
6、明文如果是字符串，加密时还有字符编码问题（UTF8/UTF16/Ansi等）
但凡有一处和所需的不一样，加密出来的结果就对不上号，还是得挨个去研究。

你贴的内容里，1/2/3/4/5都确定了（虽然4对方文档里没说是PKCS7，但你一楼写了用PKCS7，就算它是）
但6你用的TEncoding.Default.GetBytes，我估计Java里常用的是UTF8，可以改成UTF8编码试一试。

总体顺序的确是先文本转UTF8的Bytes，再BytesAddPKCS7Padding，再SM4EncryptEcbBytes，再BytesToHex，
解密则是倒过来，先HexToBytes，再SMDecryptEcbBytes，再BytesRemovePKCS7Padding，再UTF8解码。

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Yang-Ya-Chao** [comment]
好勒谢谢大哥，我试试

**Comment by Yang-Ya-Chao** [comment]
改成utf8的话，密文长度是一模一样的了，但是结果还是对不上，思路顺序应该是没问题的，其他的三方的我也对过都没问题，他这个密文我对不上，有可能是他们自己写的不是标准的sm4吧，其他原因我找不出来了

**Comment by shanzhashu** [comment]
刚看你代码还有一个要注意的点，Java的byte数组是有符号的所以对方提供的密钥有负值，比如-120，而我们加解密的Key的array[] of Byte是无符号的，你用255-120代替-120，这一点你那边能否确认正确？

**Comment by Yang-Ya-Chao** [comment]
不能确认是不是这个原因引起的，d没有负数的数组，咨询过好多人说是255-120 与-120是一致的，但是我自己并不确认，而且也没法确认是不是跟java的区别是这里造成的，算了不纠结了，谢谢大哥，sm4的思路搞明白就行了，主要是这个加密我之前没有对接出来有点梗着，所以来问问，应该是其他原因影响，而不是sm4这个加密代码本身的问题

**Comment by shanzhashu** [comment]
var
  B: Byte;
begin
  B := Byte(-120);
  Caption := IntToStr(B);

得到的结果是136，也就是说应该是256-120，而不是255。

**Comment by Yang-Ya-Chao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
