### ISSUE TITLE
Cnvcl20220601无法编译，CnRSA等多个单元出错

### ISSUE THREAD

**Issue by sxbug** [cnpack/cnvcl#20]
错误提示：在cnRSA单元里，ECN_OK，ECN_CUSTOM_ERROR_BASE 等均未定义。_CnSetLastError等函数也没有定义。请问该如何修改？谢谢

**Comment by shanzhashu** [comment]
照理都在CnConsts.pas里
烦请从github上clone或pull最新主分支代码吧。
