### ISSUE TITLE
Delphi 11.1下Cnvcl20220701无法编译，ECN_OK缺少

### ISSUE THREAD

**Issue by dreamnyj** [cnpack/cnvcl#22]
如题。这个缺少我很困惑，是否并没有测试过哦。

**Comment by shanzhashu** [comment]
比较奇怪，尝试一下更新到master分支最新点看看是否还有这个问题？
另外提提示出错的单元名是？

**Comment by tonvoo** [comment]
我也有这个问题，发版没测试过？

CnBase64

` BASE64_OK       = ECN_OK; // 转换成功`

**Comment by tonvoo** [comment]
> 我也有这个问题，发版没测试过？
> 
> CnBase64
> 
> ` BASE64_OK = ECN_OK; // 转换成功`

刚看了一下 ，原始的cnconst是有定义的，但是我用movefiles转换成了中文，中文的cnconst没有这个定义。

再检查下所有的本地化文件吧，或许还有漏的

**Comment by shanzhashu** [comment]
去年已修正其他语言版。
