### ISSUE TITLE
sm2等国密算法不能在lazarus使用

### ISSUE THREAD

**Issue by szlbz** [cnpack/cnvcl#29]
希望sm等国密算法支持linux及arm和龙芯cpu

**Comment by cnpack** [comment]
Lazarus下能够支持cnvcl中的部分加密库，请参考cnvcl\Packages\FPC3下的工程。

至于龙芯，理论上能支持，可是没有测试环境。。。

**Comment by szlbz** [comment]
你们提供的版本使用x86汇编，arm等cpu不能编译。
----- 原始邮件 -----
发件人：CnPack Team ***@***.***>
收件人：cnpack/cnvcl ***@***.***>
抄送人：szlbz ***@***.***>,  Author ***@***.***>
主题：Re:_[cnpack/cnvcl]_sm2等国密算法不能在lazarus使用_(Issue_#29)
日期：2023年03月24日 00点17分


Lazarus下能够支持cnvcl中的部分加密库，请参考cnvcl\Packages\FPC3下的工程。
至于龙芯，理论上能支持，可是没有测试环境。。。

&mdash;

**Comment by cnpack** [comment]
我们想办法看看。

**Comment by cnpack** [comment]
我们想办法看看。

**Comment by szlbz** [comment]
谢谢在 2023年3月24日，09:18，CnPack Team ***@***.***> 写道：﻿
我们想办法看看。

**Comment by shanzhashu** [comment]
x64的Linux已初步支持。

**Comment by szlbz** [comment]
辛苦您了，希望能支持非x86CPU在 2023年3月24日，23:01，Liu Xiao ***@***.***> 写道：﻿
x64的Linux已初步支持。

**Comment by szlbz** [comment]
在linux arm或龙芯无法编译sm9 demo

----- 原始邮件 -----发件人：Liu Xiao ***@***.***>
收件人：cnpack/cnvcl ***@***.***>
抄送人：szlbz ***@***.***>,  Author ***@***.***>
主题：Re:_[cnpack/cnvcl]_sm2等国密算法不能在lazarus使用_(Issue_#29)
日期：2023年03月24日 23点01分


x64的Linux已初步支持。

**Comment by shanzhashu** [comment]
没有编译环境。
请问出啥错？

**Comment by hifly0898** [comment]
> 没有编译环境。 请问出啥错？

就像lsuper所说，让Delphi支持国产化的了了无期的，Lazarus+FPC是最好的补充，希望刘兄鼎力相助，把国密加密算法迁移到龙芯CPU（Loongarch64）+UOS pro v20+Lazarus+FPC，在此谢了哈。

**Comment by szlbz** [comment]
按以下步骤可以编译sm2和sm9的demo，但不确定是否有隐患，请刘兄和cnpack团队帮忙移植到龙芯，谢谢。
![image](https://user-images.githubusercontent.com/109887617/227746435-8cbcd638-f704-4c8f-b54c-4bc07eef7d46.png)
![image](https://user-images.githubusercontent.com/109887617/227746445-f1852f52-de83-456c-84d9-42c3d0dbe7a3.png)
![image](https://user-images.githubusercontent.com/109887617/227746456-56683a24-4ad1-4cb7-b0d2-b1353e613ffb.png)
![image](https://user-images.githubusercontent.com/109887617/227746475-def4a92e-0b47-4655-9af5-056f65d2c722.png)
![image](https://user-images.githubusercontent.com/109887617/227746482-e1a810d5-dd09-4e15-a92f-53320faa907f.png)
![image](https://user-images.githubusercontent.com/109887617/227746491-88ade7a4-b3d4-41fc-a1ff-3ebca4e4f369.png)
![image](https://user-images.githubusercontent.com/109887617/227746496-29bfe9c9-28cf-48d7-9a3c-403f7d495ee6.png)
![image](https://user-images.githubusercontent.com/109887617/227746514-4bc80823-f981-485f-a510-3967e5d96134.png)
![image](https://user-images.githubusercontent.com/109887617/227746524-8b61f574-2e22-47a6-8caa-e5f1729f470d.png)
![image](https://user-images.githubusercontent.com/109887617/227746529-3d869c9c-9839-4750-a56b-80e46f77c00e.png)
![image](https://user-images.githubusercontent.com/109887617/227746535-29fb018c-a6e3-47d7-9b22-897999a2701a.png)
![image](https://user-images.githubusercontent.com/109887617/227746537-d424ebe7-8e79-479c-98db-a9ac14efb0a0.png)
![image](https://user-images.githubusercontent.com/109887617/227746545-02d0473b-ef2e-42da-81b7-fdc04d60f841.png)

**Comment by szlbz** [comment]
![image](https://user-images.githubusercontent.com/109887617/227747044-545d9162-edfc-4e57-853d-d6dba29bb34c.png)

**Comment by szlbz** [comment]
有待cnpack验证。

**Comment by szlbz** [comment]
这个方法修改不适合lazarus for win

**Comment by shanzhashu** [comment]
收到，CnVCL这部分内容要同时支持Delphi/FPC，Windows/MacOS/Linux、x86/x64/ARM、Unicode/非Unicode，确实牵一发动全身。之前未考虑过ARM，要加上的话还需想办法仔细调整各类Define。

**Comment by szlbz** [comment]
期待cnvcl的Crypto支持lazarus(win/linux,x86,arm,aarch64,loongarch64)，谢谢！

**Comment by shanzhashu** [comment]
当务之急是搭个环境验证关于ARM/龙芯等的适应修改。
看到了你论坛上打包提供的Lazarus+FPC 的Linux aarch64版和loongArch64 龙芯纯净版，
是否分别必须在ARM64的Linux上，和龙芯Linux上才能跑起来？如果是，就麻烦了，缺硬件。

**Comment by szlbz** [comment]
是的，必须在arm或龙芯才能使用。不过，只要剥离delphi和win，特别是使用汇编这部位，主要问题在cnpack.ini、cnprimenumber、cnbignumber和cnlockfree这4个文件，增加fpc和linux条件编译应该就可以。

**Comment by szlbz** [comment]
可用向日葵远程我台龙芯电脑进行验证

**Comment by shanzhashu** [comment]
好的，能否将你改动的这四个文件先发我邮箱？我检查一下要如何整合。
master@cnpack.org

**Comment by szlbz** [comment]
已发邮件

**Comment by shanzhashu** [comment]
已解决，感谢协助。
