### ISSUE TITLE
使用 FPC 编译目标为 Linux-ARM64 的程序发现 CnDES 单元一个非常奇怪的问题

### ISSUE THREAD

**Issue by winddriver** [cnpack/cnvcl#32]
编译器是最新的 FPC 3.3.1，编译时报的错误如图
![image](https://github.com/cnpack/cnvcl/assets/3221597/3817a8ab-9f3d-40cf-a15f-28046bd57f42)

估计是编译器的bug，但是可以通过调整部分代码避免该问题

我发现只要将
`procedure Encry(InData, ASubKey: array of Byte; var OutData: array of Byte);`
修改为
`procedure Encry(const InData, ASubKey: array of Byte; var OutData: array of Byte);`

这个问题就不会出现了

建议将类似的参数定义都加上 const 定义，毕竟 const 定义的话，该参数只会传指针，不会做内存拷贝，效率也会高一些

**Comment by shanzhashu** [comment]
有道理，马上改掉。

**Comment by shanzhashu** [comment]
已改正，感谢建议。
另外，Linux-ARM64平台上的验证工作可否帮我们做一下？我发邮件到winddriver@msn.com描述一下详情。
