### ISSUE TITLE
D10.4下使用加解密组件好像有问题……

### ISSUE THREAD

**Issue by tony0228** [cnpack/cnvcl#34]
Base64的加解密，得到的结果和大多数的工具对不上：
![1](https://github.com/cnpack/cnvcl/assets/11979711/bea6c729-a895-4f0c-b973-51739e16308f)
![2](https://github.com/cnpack/cnvcl/assets/11979711/da794693-4465-43da-a37d-27ed69de0f0c)

**Comment by cnpack** [comment]
试一试英文数字是否一致？

CnVcl中的例子是拿字符串的默认编码来做Base64，如果和你找的工具对不上号，要先确定对方用的是什么字符串编码，UTF8还是其他。

**Comment by tony0228** [comment]
英文字符结果是一样的

**Comment by cnpack** [comment]
那说明Base64算法本身没问题，汉字可能是UTF8导致的。

试着把例子中的MyStringToBytes函数中的：
Result := TEncoding.Default.GetBytes(Str);
改成
Result := TEncoding.UTF8.GetBytes(Str);
试一试。
